# Generated by Django 4.0.2 on 2022-03-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
