# Generated by Django 4.0.4 on 2022-06-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_product_currentprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryProduct',
            new_name='category',
        ),
    ]
