# Generated by Django 4.0.4 on 2022-06-21 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_categoryproduct_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('rate', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
                ('mssFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='auctions.product')),
                ('mssFrom', models.ManyToManyField(related_name='comentator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
