# Generated by Django 4.0.4 on 2022-06-22 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='mssFrom',
        ),
        migrations.AddField(
            model_name='comment',
            name='mssFrom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comentator', to=settings.AUTH_USER_MODEL),
        ),
    ]
