# Generated by Django 4.0.4 on 2022-06-22 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_comment_mssfrom_comment_mssfrom'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishList',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, to='auctions.product')),
            ],
        ),
    ]
