# Generated by Django 4.0.4 on 2022-06-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wishList',
            new_name='itemsList',
        ),
    ]
