# Generated by Django 4.0.4 on 2022-06-28 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_product_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bids',
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='bids',
            field=models.ManyToManyField(related_name='values', to='auctions.bid'),
        ),
    ]
