# Generated by Django 4.0.4 on 2022-06-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_product_bids_bid_product_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='totalBids',
            field=models.IntegerField(default=0),
        ),
    ]
