# Generated by Django 4.0.4 on 2022-07-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_product_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, upload_to=None),
        ),
    ]
